@ECHO OFF
set PYTHONHOME=z:\utils\Desarrollo\Entornos\Graficos\Python\Python_274
set PYTHONPATH=%PYTHONHOME%\Lib

set FLOG=c:\tmp\log_spazio_receive.log
set SPAZIO=c:\spazio
set BASEPYTHON=z:\brqx\unix\libs\python\primeur
set BASEPYTHON_OO=%BASEPYTHON%\oop
set PYTHONPATH=%PYTHONPATH%;%BASEPYTHON%\spazio
set PYTHONPATH=%PYTHONPATH%;%BASEPYTHON%\main
set PYTHONPATH=%PYTHONPATH%;%BASEPYTHON%\base
set PYTHONPATH=%PYTHONPATH%;%BASEPYTHON%\oop

set PYTHON_OO_PATH=

set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_arg
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_date
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_env
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_file
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_log
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_msg
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_parse
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_post
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_search
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_split
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_str
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_sys

set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_spa\acq
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_spa\lis
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_spa\dsp
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_spa\gen
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_rul\acq
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_rul\dsp
set PYTHON_OO_PATH=%PYTHON_OO_PATH%;%BASEPYTHON_OO%\oo_rul\gen

set PYTHONPATH=%PYTHONPATH%;%PYTHON_OO_PATH%
set PATH=%PYTHONPATH%;%PATH%
